urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import IndexView

app_name = 'news'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^search$', views.search, name='search'),
   # url(r'^(?P<location_name>(.*)+)/$', views.detail, name='detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

models.py
from django.db import models

# Create your models here.

views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView

from django.shortcuts import render

from news.NaverNews import NaverNews

# Create your views here.
class IndexView(TemplateView):
	template_name = "news/index.html"
	def get_context_data(self, **kwargs):
		top_topics = ['국정원 의혹', '한일관 대표 사망', '홍준표 서청원 녹취록', '한국당 보이콧', '홍종학 불법 증여', '카탈루냐 지방', '풍계리 핵실험', '윤송이', '경기 버스준공영제']
		context = super(IndexView, self).get_context_data(**kwargs)
		context['top_topic_list'] = top_topics
		return context

def search(request):
	query = request.GET.get("query")
	order_by = request.GET.get("order_by")
	n = NaverNews(query)
	n.fetch_articles()
	n.sort_by_time(order_by)
	top3_dict = n.plot_time_trend()
	context = { 'article_list': n.article_list,
				'top3_dict': top3_dict,
	}

	return render(request, 'news/search.html', context)

templates/news/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="{% static "news/css/materialize.min.css" %}"  media="screen,projection"/>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

	<div class="container">
	  <nav>
	    <div class="nav-wrapper blue darken-2">
	      <a href="#" class="brand-logo center">뉴스 검색!</a>
	      <ul id="nav-mobile" class="right hide-on-med-and-down">
	      </ul>
	    </div>
	  </nav>
	  <br>
	 	<div class="row">
			<form id="searchForm" action="{% url 'news:search' %}" method="get" accept-charset="utf-8">
				<div class="col s8">
					<input class="searchField" id="name" name="query" type="text" placeholder="한일관 대표 사망">
				</div>
				<div class="col s4">
					<button class="btn waves-effect waves-light" type="submit">검색
						<i class="material-icons right">search</i>
					</button>
				</div>
				<div class="col s12 center">
					<b>시간 정렬</b><br>
					<input name="order_by" type="radio" id="asc" value="asc"/>
					<label for="asc">옛날 기사부터</label>
					<input name="order_by" type="radio" id="desc" value="desc" checked />
					<label for="desc">최신 기사부터</label>
				</div>
			</form>
		</div>
		<div class="row">
			<h4>화제의 키워드</h4>
			{% for topic in top_topic_list %}
			<div class="chip"><a href="{% url 'news:search' %}?query={{ topic }}">{{ topic }}</a></div>
			{% endfor %}
		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="{% static "news/js/materialize.min.js" %}"/></script>
	</div>
</body>
</html>

templates/news/search.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="{% static "news/css/materialize.min.css" %}"  media="screen,projection"/>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<div class="container">
	<h4>검색하신 <b>{{ request.GET.query }}</b>에 대한 결과입니다.</h4>
	<a href="{% url 'news:index' %}">[처음으로]</a>
    <ul class="collection with-header">
      <li class="collection-header"><h4>핫했던 날짜 TOP 3!</h4></li>
      {% for key, value in top3_dict.items %}
      <li class="collection-item"><div>{{ key.isoformat }}<a href="#!" class="secondary-content"><span class="new badge blue" data-badge-caption="건">{{ value }}</span><i class="material-icons">send</i></a></div></li>
      {% endfor %}
    </ul>
	{% for article in article_list %}
	<div class="row">
		<div class="card hoverable light-blue darken-2">
			<div class="card-content white-text">
				{% autoescape on %}
				<span class="card-title"><b>{{ article.title }}</b></span>
				<p>{{ article.summary }}</p>
				<p>({{ article.pub_date }})</p>
				{% endautoescape %}
				<div class="card-action">
					<a href="{{ article.article_url }}">네이버 뉴스 링크</a>
					<a href="{{ article.article_original_url }}">원 기사 링크</a>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static "news/js/materialize.min.js" %}"/></script>
</html>